name: Windows CI
on: [push, pull_request]

jobs:
  run-windows-tests:
    name: Build & run tests
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
      name: Checkout Code

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.18.3'

    - name: Check Audio devices
      run: Get-CimInstance Win32_SoundDevice | fl *
    - name: Install Virtual Sound Card
      shell: powershell
      run: |
        Start-Service audio*
        Invoke-WebRequest https://github.com/duncanthrax/scream/releases/download/3.6/Scream3.6.zip -OutFile C:\Scream3.6.zip
        Extract-7Zip -Path C:\Scream3.6.zip -DestinationPath C:\Scream
        $cert = (Get-AuthenticodeSignature C:\Scream\Install\driver\Scream.sys).SignerCertificate
        $store = [System.Security.Cryptography.X509Certificates.X509Store]::new("TrustedPublisher", "LocalMachine")
        $store.Open("ReadWrite")
        $store.Add($cert)
        $store.Close()
        cd C:\Scream\Install\driver
        C:\Scream\Install\helpers\devcon install Scream.inf *Scream
    - name: Check Audio devices
      run: Get-CimInstance Win32_SoundDevice | fl *

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      with:
        vs-version: 16.5

    - name: Install example modules
      run: |
        cd example
        yarn --pure-lockfile
    - name: Build release
      run: |
        cd example
        npx react-native run-windows --release --no-packager --no-launch --logging
    - name: Start Appium server
      shell: powershell
      run: |
        cd example
        Start-Process PowerShell -ArgumentList "yarn appium"
    - name: Run tests
      run: |
        cd example
        yarn test:windows 